#!/bin/bash
#PBS -N jacobi
#PBS -j oe
#PBS -o jacobi.out
#PBS -q high
#PBS -l nodes=1:ppn=32:xe
#PBS -l walltime=00:10:00

cd $PBS_O_WORKDIR

echo "========running serial version ====="
time aprun -n 1 -N 1 ./jacobi_serial

echo "========running omp version using 8 threads ====="
export OMP_NUM_THREADS=8
time aprun -n 1 -N 1 -d 8 ./jacobi_omp

echo "========running omp version using 16 threads ====="
export OMP_NUM_THREADS=16
time aprun -n 1 -N 1 -d 16 ./jacobi_omp
